config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  get 'seraches/serach'
  get 'seraches/search'
  get 'search/search'
  root to: 'homes#top'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get 'home/about' => 'homes#about'
  resources :users, only: [:show, :edit, :update, :index] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
  end
  get '/search' => 'searches#search'
  resources :groups, only: [:index, :show, :edit, :create, :update, :new, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

   has_many :favorites, dependent: :destroy
   has_many :favorited_users, through: :favorites, source: :user
   has_many :book_comments, dependent: :destroy
  

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  attachment :image, destroy: false
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image
   validates :name, presence: true, uniqueness: true,length: { in: 2..20 }
   validates :introduction, length: { maximum: 50 }

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end
  has_many :group_users   
  has_many :groups, through: :group_users
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorited_users).
    sort {|a,b|
        b.favorited_users.includes(:favorites).where(created_at: from...to).size <=>
        a.favorited_users.includes(:favorites).where(created_at: from...to).size
      }
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       redirect_to book_path(@book), notice: 'You have created book successfully.'
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       redirect_to book_path(@book), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @groups = Group.all
  end

  def show
    @book = Book.new
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render "edit"
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @content = params['search']['content']
    @how = params['search']['how']
    @model = params['search']['model']
    @datas = search_for(@how, @model, @content)
  end

private

  def match(model, content)
    if model == 'user'
      User.where(name: content)
    elsif model == 'book'
      Book.where(title: content)
    end
  end

  def forward(model, content)
    if model == 'user'
      User.where('name LIKE ?', "#{content}%")
    elsif model == 'book'
      Book.where('title LIKE ?', "#{content}%")
    end
  end

  def backward(model, content)
    if model == 'user'
      User.where('name LIKE ?', "%#{content}")
    elsif model == 'book'
      Book.where('title LIKE ?', "%#{content}")
    end
  end

  def partical(model, content)
    if model == 'user'
      User.where('name LIKE ?', "%#{content}%")
    elsif model == 'book'
      Book.where('title LIKE ?', "%#{content}%")
    end
  end

  def search_for(how, model, content)
    case how
    when 'match'
      match(model, content)
    when 'forward'
      forward(model, content)
    when 'backward'
      backward(model, content)
    when 'partical'
      partical(model, content)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end



  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_count.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th>今日の投稿数</th>
      <th>前日の投稿数</th>
      <th colspan="3">前日比</th>
    </tr>
  </thead>
  <tbody>
    <td><%= current_user.books.where(created_at: Time.zone.now.all_day).count %></td>
    <td><%= current_user.books.where(created_at: 1.day.ago.all_day).count %></td>
    <td>
      <% if current_user.books.where(created_at: 1.day.ago.all_day).count == 0 %>
        前日の投稿はありません
      <% else %>
        <%= 100* current_user.books.where(created_at: Time.zone.now.all_day).count / current_user.books.where(created_at: 1.day.ago.all_day).count  %>%
      <% end %>
    </td>
  </tbody>
</table>

<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th>今週の投稿数</th>
      <th>先週の投稿数</th>
      <th colspan="3">前週比</th>
    </tr>
  </thead>
  <tbody>
    <td><%= current_user.books.where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day).count %></td>
    <td><%= current_user.books.where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day).count %></td>
    <td>
      <% if current_user.books.where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day).count == 0 %>
        前日の投稿はありません
      <% else %>
        <%= 100* current_user.books.where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day).count / current_user.books.where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day).count %>%
      <% end %>
    </td>
  </tbody>
</table>

app/views/books/_detail.html.erb
<table class='table'>
    <tr id="book_<%= book.id %>">
       <td>
          <%= link_to user_path(book.user) do %>
           <%= attachment_image_tag book.user, :profile_image, size: "60x60", fallback: "no_image.jpg"%><br>
           <%= book.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(book) do %>
              <%= book.title %>
            <% end %>
          </td>
          <td>
            <%= book.body %>
          </td>
          <td class="favorite-btn">
            <%= render 'favorites/favorite-btn', book: book %>
          </td>
          <td>
            コメント数：<%= book.book_comments.count %>
          </td>
          <% if book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に削除しますか？"  %></td>
          <% end %>
        </tr>
</table>

app/views/books/_form.html.erb
<%= form_with model:book, local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr id="book_<%= book.id %>">
        <td>
          <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, size: "60x60", fallback: "no_image.jpg"%>
          <% end %>
        </td>
        <td>
          <%= link_to book_path(book) do %>
            <%= book.title %>
          <% end %>
        </td>
        <td>
          <%= book.body %>
        </td>
        <td class="favorite-btn">
          <%= render 'favorites/favorite-btn', book: book %>
        </td>
        <td>
          コメント数：<%= book.book_comments.count %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'layouts/errors', obj: @book %>
    	<%= render 'books/form', book: @book %>
  		<%= link_to 'Show', book_path(@book) %> |
  		<%= link_to 'Back', books_path %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
     <h2>User info</h2>
     <%= render 'users/info', user: current_user %>
     <h2 class="mt-3">New book</h2>
     <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index', books: @books, user: @user %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
     <h2>User info</h2>
     <%= render 'users/info', user: @book.user %>
     <h2 class="mt-3">New book</h2>
     <%= render 'books/form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <div class="detail-table">
       <%= render 'books/detail', book: @book %>
      </div>
      <div class=comments-area>
        <%= render 'book_comments/comments', book: @book %>
      </div>
      <div class="new-comment">
         <%= form_with(model:[@book, @book_comment]) do |f| %>
          <%= f.text_area :comment, size:'90x5', class: "text_area" %><br>
          <%= f.submit "送信" %>
         <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/_form.html.erb
<%= form_with model: group, local: true do |f| %>
  <div class="form-group">
    <%= f.label :グループ名 %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :紹介文 %>
    <%= f.text_area :introduction, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :グループ画像 %>
    <%= f.attachment_field :image, class: "form-control-file" %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-info' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Editing Group</h3>
        <%= render 'form', group: @group %>
  </div>
</div>

app/views/groups/index.html.erb
<div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <td><%= attachment_image_tag(group, :image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
              <td><%= link_to group.name, group_path(group) %></td>
              <td><%= group.introduction %></td>
              <td>
                <% if group.owner_id == current_user.id %>
                  <%= link_to 'Edit', edit_group_path(group), class: "btn btn-sm btn-success" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

app/views/groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Create Group</h3>
        <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Group Detail</h2>
      <table class='table table-hover table-inverse'>
        <tr>
          <td><%= attachment_image_tag(@group, :image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
          <td><%= @group.name %></td>
          <td><%= @group.introduction %></td>
          <td>
            <% if @group.owner_id == current_user.id %>
              <%= link_to 'Edit', edit_group_path(@group), class: "btn btn-sm btn-success" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/searches/_search.html.erb
<div class="row">
  <div class="col-md-12 text-center" style="margin-top: 25px;">
    <% if user_signed_in? %>
      <%= form_with url:search_path, method: :get, local: true do |f| %>
        <%= f.text_field 'search[content]' %>
        <%= f.select 'search[model]', options_for_select({ "User" => "user", "Book" => "book" }) %>
        <%= f.select 'search[how]', options_for_select({ "完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"  }) %>
        <%= f.submit :"検索" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/searches/search.html.erb
<div class="container">
  <div class="col-xs-12">
    <% if @model == "user" %>
    <h2>Users search for '<%= @content %>'</h2>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Name</th>
                <th>Introduction</th>
            </tr>
        </thead>
    <% @datas.each do |user| %>
        <tbody>
            <tr>
                <th>
                    <%= attachment_image_tag(user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40') %>
                </th>
                <th>
                    <%= user.name %>
                </th>
                <th>
                    <%= user.introduction %>
                </th>
            </tr>
        </tbody>
    <% end %>
    <% elsif @model == "book" %>
    <h2>Books search for '<%= @content %>'</h2>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
            </tr>
        </thead>
        <% @datas.each do |book| %>
        <tbody>
            <tr>
                <th>
                    <%= attachment_image_tag(book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40') %>
                </th>
                <th>
                    <%= book.title %>
                </th>
                <th>
                    <%= book.body %>
                </th>
            </tr>
        </tbody>
        <% end %>
    <% end %>
    </table>
  </div>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, size: "60x60", fallback: "no_image.jpg"%></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if current_user != user %>
           <%= render 'relationships/follow_button', user: user %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr>
    <%= attachment_image_tag user, :profile_image, size: "100x100", fallback: "no_image.jpg"%>
  </tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%= link_to user_followings_path(user) do %>
        <%= user.followings.count %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to user_followers_path(user) do %>
        <%= user.followers.count %>
      <% end %>
    </th>
  </tr>
</table>

 <div class='row'>
  <% if current_user != user %>
    <%= render 'relationships/follow_button', user: user %>
  <% else %>
    <%= link_to "", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <%= render 'layouts/errors', obj: @user %>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model:@user, local:true do |f| %>

        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: "form-control name" %>
        </div>
        <div class="form-group">
          <%= f.label :Image %><br>
          <%= f.attachment_field :profile_image, class: "form-control profile_image" %>
        </div>
        <div class="form-group">
          <%= f.label :Introduction %><br>
          <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
     <h2>User info</h2>
     <%= render 'users/info', user: current_user %>
     <h2 class="mt-3">New book</h2>
     <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <div><%=link_to "グループを作成する",new_group_path %> | <%=link_to "グループ一覧",groups_path %></div>
      <%= render 'users/index', users: @users %>
    </div>
 </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
     <h2>User info</h2>
     <%= render 'users/info', user: @user %>

     <h2 class="mt-3">New book</h2>
     <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>　
      <%= render 'books/index', books: @books %>
      <h2>投稿数</h2>
      <%= render 'books/count' %>
    </div>
  </div>
</div>